### ISSUE TITLE
[Feature/Improvement] Increase seconds or add minutes in the timer

### ISSUE THREAD

**Issue by Antitoxic0** [a-mabe/OpenHIIT#100]
**Purpose:** As a user, I'd like to use this app also for other types of workouts that require sets longer than 120 seconds

**More details:** For example WOD such as "AMRAP" that could last 10 minutes, cyclette sets many minutes long or "FOR TIME" workouts in which you have to end it by the time given

**Acceptance Criteria:**

**Comment by a-mabe** [comment]
Thank you for the feature request, your input is appreciated! I will get this added to the todo list, any implementation updates will be added to this issue

**Comment by gagzzz** [comment]
Hello!
I'd like this feature as well :)
Maybe a timer that can be set typing numbers, such as the one in the default android Clock app?


Thank you very much :)

**Comment by a-mabe** [comment]
Adding info from another feature request for longer time intervals here. Request from @not-programmer98: https://github.com/a-mabe/OpenHIIT/issues/111

> **Purpose:** As a user, I want to use this app in studying. This requires longer periods of time like 45 minutes study and 5 
> minutes break
>
> **More details:** More informations about this [here](https://en.m.wikipedia.org/wiki/Pomodoro_Technique)

All updates for increasing the max allowed interval time will be tracked here.
