### ISSUE TITLE
Icon too small (and README with non-transparent background)

### ISSUE THREAD

**Issue by Porkepix** [a-mabe/OpenHIIT#101]
**Describe the bug**
Not a user of the application here, but I saw it on the new fresh updates in F-droid (with Izzy's repo) and icon looks a lot smaller than all the other ones. Probably because the icon itself is surrounded by too much empty space compared to its own size. This can somehow be seen on your README in the repo, where the icon would also be benefiting from transparent background, because when you use dark themed GitHub, you see the icon into a very big white square background. The icon's size should be increased compared to the square's size, or the square's size decreased.

**Expected behavior**
Icon should have a scaling similar to other applications, and a transparent background everywhere.

I don't think screenshots are necessary here, but lemme know if you really need some.

**Comment by a-mabe** [comment]
Thank you for the heads up @Porkepix. Is this an issue with the app itself or with how the image appears on websites? I have not yet taken the time to create assets outside of what is required by Google Play and the App Store
