### ISSUE TITLE
[Integration Test] Complete the integration test for creating and saving a Workout

### ISSUE THREAD

**Issue by a-mabe** [a-mabe/OpenHIIT#113]
**Test:** Create a workout

**Scenario outline:**
1. Start the app.
2. Select the `+`.
3. Select add a workout.
4. Use all UI elements to adjust the workout settings on the creation page.
5. Continue.
6. Add exercises.
7. Continue.
8. Use all UI elements to adjust the work and rest times.
9. Continue.
10. Use all UI elements to select audio.
11. Continue.
12. Verify that the created workout appears on the home screen.

**Verify that:**
1. All number pickers and text inputs work as expected.
2. The workout is available to select from the app's home screen.

**Comment by madbehaviorus** [comment]
I think before I open a bugreport it is better to write it here:

If I build and deposit a new workout and try to change the practises, I get a white screen and nothing happens.
I try it multiple times withe the same effect.

I use Android 13 without google services.

**Comment by a-mabe** [comment]
Hi @madbehaviorus, please do open a bug report and include as many details as possible. I'd love to be able to address any bugs in the next release 😄

**Comment by madbehaviorus** [comment]
I don't can use logcat as root and I don't have TWRP as recovery, however it is not possible to get some logs.

Steps to reproduce:
1) create a workout with some practices
2) open it and try to change the number of practices upper than before

If I change the number of practices lower than before, it is possible and I don't get an error.

**Comment by a-mabe** [comment]
Closed in #123
