### ISSUE TITLE
Impossible to increase the number of exercises from an existing workout

### ISSUE THREAD

**Issue by madbehaviorus** [a-mabe/OpenHIIT#115]
**Describe the bug**
If I build and deposit a new workout and try to change the practices, I get a white screen and nothing happens after it.
I try it multiple times with the same effect.

**To Reproduce**
Steps to reproduce:

   -  create a workout with some practices
    - open it and try to change the number of practices upper than before

If I change the number of practices lower than before, it is possible and I don't get an error.

**Expected behavior**
Accept the changed number of practices.

**Screenshots**
[![Screen.png](https://i.postimg.cc/xdDmgT2d/Screen.png)](https://postimg.cc/DS6mwhmV)

**Device and Operating System (please complete the following information):**
     - Fairphone 4
    - Android 13 (official CalyxOS 4.15.0 - without google services)

**Additional context**
I don't can use logcat as root and I don't have TWRP as recovery, however it is not possible to get some logs.

**Comment by a-mabe** [comment]
Thank you for the detailed bug report @madbehaviorus! I will try to get this fixed in the next release
