### ISSUE TITLE
[Feature/Improvement] Revert Icon

### ISSUE THREAD

**Issue by Toiletmason** [a-mabe/OpenHIIT#125]
**Purpose:** The new icon is terrible and makes it look like an app from the early 2010s

**Comment by a-mabe** [comment]
Thanks for sharing your thoughts on the new icon! Feel free to open a new issue with your proposed icon design, or even better, submit a pull request if you have the skills to create the icon. We appreciate your engagement and look forward to any positive contributions you might have to this open source project.

**Comment by a-mabe** [comment]
Closing in favor of #134
