### ISSUE TITLE
[Feature/Improvement] Skip Intervals During a Workout

### ISSUE THREAD

**Issue by Milchreis** [a-mabe/OpenHIIT#128]
**Purpose:** 
As a user, I want to skip to a specific interval by clicking on it, because I stopped the workout by swiping on the screen. 

**More details:** 
The workout / interval starts every time on the beginning. Sometimes I want to skip some parts. For me it would be perfect, to move to the part which I click on. 

**Acceptance Criteria:** 
Intervals are skipped by click on later interval.

BTW: it's a really nice app and works great, thank you 😊👍

**Comment by a-mabe** [comment]
Thank you for taking the time to open a feature request, your input and support is appreciated! I will get this added to the todo list

**Comment by a-mabe** [comment]
Blocked by / relates to https://github.com/a-mabe/background_hiit_timer/issues/22
