### ISSUE TITLE
[Feature/Improvement] Duplicate workout

### ISSUE THREAD

**Issue by blabohm** [a-mabe/OpenHIIT#129]
**Purpose:** Allow users to duplicate existing workouts instead of starting from scratch each time.

**More details:** Sometimes I want to implement some modifications to a workout (e.g. change some of the exercises). But often I would prefer not to change the existing workout for various reasons (getting variation in a routine, testing exercises...). In the current version of the App I would have to either modify the existing workout or start a new workout from scratch to e.g. test minor changes. 
Adding a duplication option would facilitate this process. 

**Acceptance Criteria:**
This feature could be implemented by either:
1.) adding a drop down menu when long pressing a workout/timer with a "duplicate" option. Or 
2.) by adding a "duplicate existing workout" feature in the "new workout" menu.

Thanks for the awesome App! I use it it on an almost daily basis :)

**Comment by a-mabe** [comment]
I appreciate the feature request, I will get this added to the todo list. Thank you for your support!

**Comment by Krunal-375** [comment]
I would like to add this feature please assign me these issue

**Comment by a-mabe** [comment]
Hey @Krunal-375, thank you for contributing, I have assigned you the issue
