### ISSUE TITLE
[Feature/Improvement] Volume control

### ISSUE THREAD

**Issue by Daichi09** [a-mabe/OpenHIIT#136]
**Purpose:** You have a nice simple app but I find the beeps to be way too loud and I want to be able to play other media that uses the same Android media volume bar while a timer is going in the background.

I imagine there could be a drop down with 10% volume increments or of course a slider if that's just as easy.

**Comment by a-mabe** [comment]
Thanks for raising this issue! Your interest in the project is appreciated. 🚀 Please note that all issues are considered and will be implemented eventually, user feedback is important 📈.

Please keep in mind that our contributors are volunteers who generously contribute their time and skills to improve this project. 

➡️ Here's how you can help:

🎨 **Not a coder? Contribute with Design/UI:**
If coding isn't your thing, no worries! Your creative input is valuable. You can help by creating UI mockups or submitting designs for the application's UI, icons, or any other visual elements.

💻 **Open a Pull Request (PR):**
If you are comfortable with coding, consider submitting a pull request to address this issue.

🗣️ **Spread the Word:**
Share your positive experiences with our project or let others know about the open issues you find interesting. Building a strong community is crucial for the success of any open source project.

Every contribution counts! Feel free to ask for guidance.
