### ISSUE TITLE
[Feature/Improvement] Icon's broken on Android

### ISSUE THREAD

**Issue by ndesgranges** [a-mabe/OpenHIIT#137]
**Purpose:** As a user, I...
As images can save thousand words :
![Screenshot_20240202_155133_One UI Home](https://github.com/a-mabe/OpenHIIT/assets/62695225/952cc305-c1cb-4719-a37b-f1757f7e0f66)

See how the icon looks old and not consistent with the UI and broken on the edges ?

Just for reference: that's how it looks on the store (droidify) 

![Screenshot_20240202_155209_Droid-ify](https://github.com/a-mabe/OpenHIIT/assets/62695225/09ff8232-bd4f-4ee7-9243-24f0858662c0)

**More details:** Some more details on the feature/improvement

As a UI designer : mobile Icons usually don't take the full space, instead try having an icon that can work inside round shapes, rounded corners and square icons. Most of the time, it is best to limit the number of colors for a modern look. The background can be a solid color or a background, this choice might differ according to the target phone

**Acceptance Criteria:**
An icon that looks "good" on any phone.

**Comment by a-mabe** [comment]
Thanks for raising this issue! Your interest in the project is appreciated. 🚀 Please note that all issues are considered and will be implemented eventually, user feedback is important 📈.

Please keep in mind that our contributors are volunteers who generously contribute their time and skills to improve this project. 

➡️ Here's how you can help:

🎨 **Not a coder? Contribute with Design/UI:**
If coding isn't your thing, no worries! Your creative input is valuable. You can help by creating UI mockups or submitting designs for the application's UI, icons, or any other visual elements.

💻 **Open a Pull Request (PR):**
If you are comfortable with coding, consider submitting a pull request to address this issue.

🗣️ **Spread the Word:**
Share your positive experiences with our project or let others know about the open issues you find interesting. Building a strong community is crucial for the success of any open source project.

Every contribution counts! Feel free to ask for guidance.
