### ISSUE TITLE
[Feature/Improvement] An ability to break current interval and start the next one

### ISSUE THREAD

**Issue by akaunderr** [a-mabe/OpenHIIT#138]
**Purpose:** As a user, I would like to be able to go to the next interval without waiting for completion.

**More details:** Just another button near to the button Pause

Thanks for such simple but great app.

**Comment by a-mabe** [comment]
Thanks for raising this issue! Your interest in the project is appreciated. 🚀 Please note that all issues are considered and will be implemented eventually, user feedback is important 📈.

Please keep in mind that our contributors are volunteers who generously contribute their time and skills to improve this project. 

➡️ Here's how you can help:

🎨 **Not a coder? Contribute with Design/UI:**
If coding isn't your thing, no worries! Your creative input is valuable. You can help by creating UI mockups or submitting designs for the application's UI, icons, or any other visual elements.

💻 **Open a Pull Request (PR):**
If you are comfortable with coding, consider submitting a pull request to address this issue.

🗣️ **Spread the Word:**
Share your positive experiences with our project or let others know about the open issues you find interesting. Building a strong community is crucial for the success of any open source project.

Every contribution counts! Feel free to ask for guidance.

**Comment by a-mabe** [comment]
Closing in favor of #128
