### ISSUE TITLE
Exercise names not shown

### ISSUE THREAD

**Issue by Milchreis** [a-mabe/OpenHIIT#144]
**Describe the bug**
Since the last release the list doesn't contains the configured names of the different exercises.
In the previous releases I could see the next work and could prepare me in the rest. 

**To Reproduce**
Start a workout. 

**Screenshots**
If applicable, add screenshots to help explain your problem
![Screenshot_20240322_193930](https://github.com/a-mabe/OpenHIIT/assets/544436/f3023ec0-49c9-4758-a754-486b04fc40c0)
.
![Screenshot_20240322_194442](https://github.com/a-mabe/OpenHIIT/assets/544436/dd0ca85c-979d-4e9e-bc1c-22ee1ea1709a)

**Device and Operating System (please complete the following information):**
 - Device: huawei p30 lite
 - OS: Android 11?

**Additional context**
Thank you for the latest release and the new features. 😊👍

**Comment by a-mabe** [comment]
Thank you for opening this issue, the detail included is appreciated too, helps to fix it fast 😁 

Release is running now: https://github.com/a-mabe/OpenHIIT/actions/runs/8396298714

Screenshots of fix here: https://github.com/a-mabe/OpenHIIT/pull/145
