### ISSUE TITLE
[Feature/Improvement] Landscape mode

### ISSUE THREAD

**Issue by Milchreis** [a-mabe/OpenHIIT#157]
**Purpose:**
As a user, I want to have a large landscape mode to see all important information.

**More details:**
Here is mockup for potenial layout in landscape, which provides larger text:
![grafik](https://github.com/a-mabe/OpenHIIT/assets/544436/084ae60d-d7c9-4f78-9372-1599d6958e0d)

**Acceptance Criteria:**
Current workout is more readable in landscape on a distance.

**Comment by a-mabe** [comment]
Thanks for raising this issue! The mockup is much appreciated; it really helps to visualize the suggested change

**Comment by a-mabe** [comment]
Working this in with UI changes needed for #136
