### ISSUE TITLE
[Refactor] Follow Proper Naming Conventions

### ISSUE THREAD

**Issue by a-mabe** [a-mabe/OpenHIIT#39]
- Use snake_case (lowercase with underscores) for libraries, directories, packages, and source files.
- Start private variable names with underscores.
- Use lowerCamelCase for functions, methods, constants, variables, parameters, and named parameters.
- Use UpperCamelCase for classes, types, extension names, and enums.

**Comment by alastairrmcneill** [comment]
heya @a-mabe are you looking for support on this issue still?

**Comment by alastairrmcneill** [comment]
Sure thing @a-mabe please assign it to me. 

How would you like the methods and functions named?

**Comment by a-mabe** [comment]
Thank you @alastairrmcneill, I have assigned the issue to you. Please name methods and functions using lowerCamelCase
