### ISSUE TITLE
[Bug] Timer on iOS leaves white space on top and bottom

### ISSUE THREAD

**Issue by a-mabe** [a-mabe/OpenHIIT#47]
Screenshot on iPhone13
![IMG_9141 jpg](https://github.com/a-mabe/OpenHIIT/assets/39250511/210874a2-dd83-4355-9ff3-e947d7939408)

Screenshot on iPhone 5
![IMG_0636 jpg](https://github.com/a-mabe/OpenHIIT/assets/39250511/9bac9eee-bb3b-4c4b-b2c3-22172f2e3bbb)

**Acceptance Criteria:**
- Background color is consistent on iOS

**Comment by alastairrmcneill** [comment]
Hi @a-mabe I have found how to fix this issue, please can you assign this one to me?

**Comment by alastairrmcneill** [comment]
Heya @a-mabe done this one.

**Comment by a-mabe** [comment]
Thank you @alastairrmcneill! I merged your fix for this
