### ISSUE TITLE
[Feature/Improvement] Alert the user when there are no workouts to show on the home screen

### ISSUE THREAD

**Issue by a-mabe** [a-mabe/OpenHIIT#52]
**Purpose:** As a user, I would like to know that the app has loaded properly even if there are no workouts to display.

**More details:** Currently, upon starting the app for the first time, the home screen appears blank since there are no saved workouts to display. Display a message like "No saved timers" so that the user is aware that the app is working as expected.

**Acceptance Criteria:**
- When there are no saved workouts/timers, a message such as "No saved timers" is displayed.

**Comment by alastairrmcneill** [comment]
Heya @a-mabe please can you assign this one to me? When I was refactoring I noticed this and was going to say something but realised there is already an open issue

**Comment by a-mabe** [comment]
@alastairrmcneill I assigned you the issue, thank you for the help!
