### ISSUE TITLE
[Feature/Improvement] Increase the max allowed number of exercises

### ISSUE THREAD

**Issue by a-mabe** [a-mabe/OpenHIIT#72]
**Purpose:** As a user, I would like to create an interval timer or workout with more than 50 work intervals.

**More details:** Currently, the Number of exercises picker only goes up to 50. Increase this to 100 and verify that no issues are introduced, e.g. performance issues when running a workout with 100 exercises.

**Acceptance Criteria:**
- Number of exercises picker for both creating a workout and creating an interval is increased to 100 (or less if issues are introduced with the number being as high as 100)
- Verified that the app does not experience performance issues with the new max number of exercises

**Comment by kirbyboxboat** [comment]
Hello Sir/Madam, I might be interested in taking on this issue. Let's connect!

**Comment by a-mabe** [comment]
Hi @kirbyboxboat, thank you for contributing, please feel free to fork the repo and open a PR. If you need an intro to the codebase feel free to reach out and we can sync up
