### ISSUE TITLE
[Feature/Improvement] Simplify setup of workouts with rest periods

### ISSUE THREAD

**Issue by andreas1107** [a-mabe/OpenHIIT#94]
**Purpose:** As a user, I would like to be able to program hiit workouts using a standard set of timings:

1. Sets
2. Reps
3. Rest between reps
4. Rest between sets
5. Warm-up / cool-down

**More details:** Some more details on the feature/improvement

See for example the screenshot which implements 1-4 above (but not 5).

It makes it very easy to schedule a program and I are directly how long it will take.

Doing this for 6 sets or 5 reps (30 intervals), with 30 second break between each set and 10 second rest between reps, using the current workout feature, is very cumbersome. 

Screenshot from outdated Fdroid app: https://github.com/kwantam/batsHIIT

**Acceptance Criteria:**

It is possible to specify in the interval timer screen:

1. Sets
2. Reps
3. Rest between reps
4. Rest between sets
5. Warm-up / cool-down

Thank you! 

![Screenshot_20231108-065852_Bats! HIIT](https://github.com/a-mabe/OpenHIIT/assets/34312687/7a540cb6-9d83-45a3-957f-5690c9690143)

**Comment by a-mabe** [comment]
Hi @andreas1107, thank you for the feature request, your input is appreciated. I'll add this to the todo list and keep this issue updated with implementation progress
